post:
  resource: "@PostBundle/Controller/"
  type: annotation

user:
  resource: "@UserBundle/Controller/"
  type: annotation

authentication:
  resource: "@UserBundle/Controller/Auth"
  type: annotation


app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout
