authentication:
    resource: "@AuthenticationBundle/Controller/"
    type:     annotation
    prefix:   /

post:
  resource: "@PostBundle/Controller/"
  type: annotation

user:
  resource: "@UserBundle/Controller/"
  type: annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout
